GET http://localhost:5000/users

###
GET http://localhost:5000/users/2

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Ria",
    "email":"Ria@gmail.com",
    "gender": "Female"
}


###
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
    "name":"khamdan farizqi",
    "email":"khamdan@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/users/1